# Generated by Django 4.2.3 on 2024-07-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_project', '0002_forgotpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpass',
            name='forgot_pass_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
